apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  namespace: x3dh-project
data:
  # This JSON pre-configures the connection to database
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "X3DH HA Cluster",
          "Group": "Servers",
          "Port": 5432,
          "Username": "x3dh_user",
          "Host": "x3dh-db-cluster-rw",
          "MaintenanceDB": "x3dh_db",
          "SSLMode": "require"
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: x3dh-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:9.11
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "512Mi"
            cpu: "700m"
        env:
        # Credentials to log into the pgAdmin Web UI
        - name: PGADMIN_DEFAULT_EMAIL
          value: "<YOUR_EMAIL>"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "<YOUR_PASSWORD>"
        volumeMounts:
        - name: servers-conf
          mountPath: /pgadmin4/servers.json
          subPath: servers.json
      volumes:
      - name: servers-conf
        configMap:
          name: pgadmin-config
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: x3dh-project
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  selector:
    app: pgadmin