apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: x3dh-db-cluster
  namespace: x3dh-project
spec:
  instances: 3 # 1 Primary + 2 Replicas

  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  postgresql:
    parameters:
      timezone: 'Europe/Rome'
  
  storage:
    size: 2Gi
    storageClass: standard

  bootstrap:
    initdb:
      database: x3dh_db
      owner: x3dh_user
      
  primaryUpdateStrategy: unsupervised
  monitoring:
    enablePodMonitor: true